#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Nov  7 16:49:05 2023
#

import wx
from bp_from_json import blueprint

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


################################################################
def fix_recipe(book):
    for bp in book.get_all_bp(onedimensional=True, blueprint_only=True):
        for entity in bp.get_entities():
            if "oil-refinery" in entity.read_name():
                if entity.read_recipe() == "basic-oil-processing":
                    entity.set("recipe", "advanced-oil-processing")


################################################################


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        # self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_RICH2)
        # sizer_1.Add(self.text_ctrl_1, 10, wx.EXPAND, 0)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "button_1")
        sizer_1.Add(self.button_1, 0, 0, 0)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_RICH2)
        sizer_1.Add(self.text_ctrl_2, 10, wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.button_1_on_click, self.button_1)
        # end wxGlade

    def button_1_on_click(self, event):  # wxGlade: MyFrame.<event_handler>
        print()

        # Читаем текст
        text = ""
        if wx.TheClipboard.Open():
            if wx.TheClipboard.IsSupported(wx.DataFormat(wx.DF_UNICODETEXT)):
                data = wx.TextDataObject()
                if wx.TheClipboard.GetData(data):
                    text = data.GetText()
                else:
                    text = ""
            wx.TheClipboard.Close()

        # print(text)
        bp = blueprint.from_string(text)
        fix_recipe(bp)
        text = bp.to_str()
        self.text_ctrl_2.AppendText("copied {}\n".format(len(text)))
        if wx.TheClipboard.Open():
            if wx.TheClipboard.IsSupported(wx.DataFormat(wx.DF_UNICODETEXT)):
                data = wx.TextDataObject()
                data.SetText(text)
                wx.TheClipboard.SetData(data)
            wx.TheClipboard.Close()

        event.Skip()


# end of class MyFrame


class MyApp(wx.App):
    def OnInit(self):
        self.MainWin = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.MainWin)
        self.MainWin.Show()
        return True


# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
